### ISSUE TITLE
Помощь в задании по авторизации (Stepic)

### ISSUE THREAD

**Issue by freedomserg** [vitaly-chibrikov/stepic_java_webserver#2]
Виталий, добрый день. Спасибо за курс по веб-программированию. 
У меня возник вопрос в задании по авторизации:  как из одной и той же формы для ввода логина/пароля в index.html, отправлять запросы на разные сервлеты, которые слушают на signin и signup?
В index.html в форме мы указываем конкретный сервлет, на который отправляется запрос, например:

<form action="/signup" method="POST">
    Login: <input type="text" name="login"/>
    Password: <input type="password" name="password"/>
    <input type="submit" value="Submit">
</form>

Здесь указывается, что запрос уходит на signup, т.к.  action="/signup". Как тогда с этой же формы отправить запрос на signin?

**Comment by isatimur** [comment]
в общем это не правильный подход, должно быть две формы, если хотите отображать их можно на одной странице либо на нескольких. Если это нужно только для теста, то лучше вам попробывать Postman, в таких ситуациях очень полезен.

**Comment by freedomserg** [comment]
Спасибо, разобрался
